apiVersion: v1
kind: Pod
metadata:
  name: podconfig
  labels:
    environment: production
    app: expense
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    configMap:
      name: expensevalues